### ISSUE TITLE
search feature

### ISSUE THREAD

**Issue by paolobenve** [paolobenve/myphotoshare#72]
Thinking on how to implement a search feature: we need a search virtual folders system, the 3rd virtual folders system after date and gps ones: the folders correspond to the words to search

In the scanner:

- for every word in the media name, add the media to the corresponding search folder
- for every word in the physical folder name, add the folder to the corresponding search folder as a subalbum

In js:

- when performing a search on one or more words, read the album(s) json files, intersect media and subalbums and save the result in a new js album with an appropriate name, and show it
- when showing a media from search, permit switching to the corresponding pyhisical folder, date and gps folders. If this switch is made, the user cannot go back to the search he/she came from.

**Comment by pmetras** [comment]
Can't the search be done entirely on the JavaScript side?

Or at least it depends on the type of search you want to have:
* Classification of photos by tags: in that case, the virtual folders that you describe is interesting because the user can browse by tag, moving from one key word to another one. Because we know in advance all the possible search terms, they can be pre-processed by the scanner.
* Search on free text, for example on a word taken from the description or the tags: in that case, I don't think there's a need for a virtual folder. The user only wants to see the list of photos that matched the search term. But switching to the views by date or GPS would be impossible. And this can be done probably in JavaScript only.

**Comment by paolobenve** [comment]
it seems to me that a free word search in js would requiere to read all the physical folders json files... It looks too time consuming with my 35,000 media and 1300 folders...

**Comment by paolobenve** [comment]
I'm almost ready!!!

**Comment by paolobenve** [comment]
it's in master, working for albums and media, 

The implementation works with words taken from media/album name, title, description, tags, removing punctuation and numbers

Permits whole word and inside words search, considering accents and capitals or not

To do: when clicking on a search album, the normal album is opened, while it should remain on search mode

**Comment by paolobenve** [comment]
@pmetras can you give it a try?

**Comment by pmetras** [comment]
This is really great! I don't know of any other static gallery with these features!!!

I corrected a small bug and it's working very well now on my small test gallery. I have to continue indexing my photos and adding metadata to see how it scales. Now the scanner creates a *lot* of index files in the cache folder. Will we encounter any OS/directory limit that will require sharding like for the picture files?

I can add support for stop words. Many words must not be indexed because there are too frequent and don't bring meaning like pronoun, articles, propositions, etc. We can use public lists like https://github.com/stopwords-iso. It'll reduce the number of index files created.

**Comment by pmetras** [comment]
Another interesting search feature but I don't know if it can be done easily is search with logical AND. Looking for media were word1 AND word2 are *both* present. This is useful when you have photos with too many items in the result sets for word1 or word2 to browse them, but where the intersection is small and can be browsed.

**Comment by paolobenve** [comment]
> Another interesting search feature but I don't know if it can be done easily is search with logical AND. Looking for media were word1 AND word2 are both present. This is useful when you have photos with too many items in the result sets for word1 or word2 to browse them, but where the intersection is small and can be browsed.

after making a search, the "any word" option is showed: selecting/unselecting it makes OR/AND search

**Comment by paolobenve** [comment]
@pmetras get current master code, a bug prevented treewalker from finishing, and so thumbnail were always generated but json files not updated

**Comment by paolobenve** [comment]
it's ok! :-)
